// prisma/seed-duel.ts
// Source de vérité + seed des Duels intégrés ("Ceci ou Cela" de base).
// Importé côté serveur/seed uniquement (jamais dans le bundle client). Au runtime
// le jeu lit les Duels depuis la DB via /api/duel.
// seedDuelDecks est idempotent : upsert par id stable `builtin_<cat.id>` +
// remplacement des items. Owner = bot random@quiz.app.
import type { PrismaClient } from '../src/generated/prisma/client';
import { DuelItem, DuelCategory, isEmoji } from '../src/lib/duel/types';

// Helpers
const poke = (id: number, name: string): DuelItem => ({
    name,
    img: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`,
});

const flag = (code: string, name: string): DuelItem => ({
    name,
    img: `https://flagcdn.com/w320/${code}.png`,
});

export const CATEGORIES: DuelCategory[] = [
    {
        id: 'pokemon',
        title: 'Le meilleur Pokémon',
        emoji: '⚡',
        items: [
            poke(25, 'Pikachu'), poke(6, 'Dracaufeu'), poke(9, 'Tortank'), poke(3, 'Florizarre'),
            poke(94, 'Ectoplasma'), poke(149, 'Dracolosse'), poke(448, 'Lucario'), poke(133, 'Évoli'),
            poke(150, 'Mewtwo'), poke(143, 'Ronflex'), poke(282, 'Gardevoir'), poke(658, 'Amphinobi'),
            poke(384, 'Rayquaza'), poke(445, 'Carchacrok'), poke(196, 'Mentali'), poke(197, 'Noctali'),
            // Ajouts
            poke(59, 'Arcanin'), poke(131, 'Léviator'), poke(144, 'Artikodin'), poke(145, 'Électhor'),
            poke(146, 'Sulfura'), poke(151, 'Mew'), poke(248, 'Tyranocif'), poke(380, 'Latias'),
            poke(381, 'Latios'), poke(385, 'Jirachi'), poke(483, 'Dialga'), poke(484, 'Palkia'),
            poke(491, 'Darkrai'), poke(493, 'Arceus'), poke(649, 'Genesect'), poke(1007, 'Ogerpon'),
            // Ajouts
            poke(257, 'Braségali'), poke(376, 'Métalosse'), poke(359, 'Absol'), poke(778, 'Mimiqui'),
            poke(887, 'Lanssorien'), poke(700, 'Nymphali'), poke(681, 'Exagide'), poke(487, 'Giratina'),
            poke(716, 'Xerneas'), poke(717, 'Yveltal'), poke(888, 'Zacian'), poke(890, 'Éthernatos'),
        ],
    },
    {
        id: 'hokage',
        title: 'Le meilleur Hokage de Konoha',
        emoji: '🍥',
        items: [
            { name: 'Hashirama Senju (1er)', img: 'https://static.wikia.nocookie.net/naruto/images/2/2e/Kid_Hashirama.png/revision/latest?cb=20230322145136' },
            { name: 'Tobirama Senju (2e)', img: 'https://static.wikia.nocookie.net/naruto/images/7/70/Kid_Tobirama.png/revision/latest?cb=20230322145433' },
            { name: 'Hiruzen Sarutobi (3e)', img: 'https://static.wikia.nocookie.net/naruto/images/e/e8/Young_Hiruzen_Mobile.png/revision/latest?cb=20210422155026' },
            { name: 'Minato Namikaze (4e)', img: 'https://static.wikia.nocookie.net/naruto/images/e/eb/Minato_Jonin.png/revision/latest?cb=20230510153913' },
            { name: 'Tsunade (5e)', img: 'https://static.wikia.nocookie.net/naruto/images/6/62/Kid_Tsunade.png/revision/latest?cb=20230407050656' },
            { name: 'Kakashi Hatake (6e)', img: 'https://static.wikia.nocookie.net/naruto/images/2/27/Kakashi_Hatake.png/revision/latest?cb=20251019002845' },
            { name: 'Naruto Uzumaki (7e)', img: 'https://static.wikia.nocookie.net/naruto/images/d/d6/Naruto_Part_I.png/revision/latest?cb=20251228135525' },
            { name: 'Danzō (intérim)', img: 'https://static.wikia.nocookie.net/naruto/images/1/17/Danz%C5%8D.png/revision/latest?cb=20171028185149' },
            // Ajouts
            { name: 'Itachi Uchiha (intérim)', img: 'https://static.wikia.nocookie.net/naruto/images/2/2e/Itachi_Part_1.png/revision/latest' },
        ],
    },
    {
        id: 'streamers',
        title: 'Le meilleur streamer FR',
        emoji: '🎮',
        items: [
            { name: 'Squeezie', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Squeezie_Zack_en_Roue_Libre_2025.png/330px-Squeezie_Zack_en_Roue_Libre_2025.png' },
            { name: 'Gotaga', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Gotaga_2026.jpg/330px-Gotaga_2026.jpg' },
            { name: 'ZeratoR', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/ZeratoR%2C_lors_du_ZEVENT_2025.jpg/330px-ZeratoR%2C_lors_du_ZEVENT_2025.jpg' },
            { name: 'Antoine Daniel', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Antoine_Daniel_-_N%C3%A9oCast2_-_3_%28cropped%29.jpg/330px-Antoine_Daniel_-_N%C3%A9oCast2_-_3_%28cropped%29.jpg' },
            { name: 'Etoiles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Etoiles_%28Rayenne_Guendil%29_lors_du_ZEVENT_2025.jpg/330px-Etoiles_%28Rayenne_Guendil%29_lors_du_ZEVENT_2025.jpg' },
            { name: 'Ponce', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Aur%C3%A9lien_Gilles_%28Ponce%29_lors_du_ZEVENT_2025.jpg/330px-Aur%C3%A9lien_Gilles_%28Ponce%29_lors_du_ZEVENT_2025.jpg' },
            { name: 'Kameto', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Kameto_ZERL.jpg/330px-Kameto_ZERL.jpg' },
            { name: 'AmineMaTue', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/AmineMaTu%C3%A9%2C_De_Twittos_%C3%A0_Top_Streameur_-_Zack_en_Roue_Libre_avec_AmineMaTu%C3%A9_%28S05E04%29_2-49_%28cropped%29.png/330px-AmineMaTu%C3%A9%2C_De_Twittos_%C3%A0_Top_Streameur_-_Zack_en_Roue_Libre_avec_AmineMaTu%C3%A9_%28S05E04%29_2-49_%28cropped%29.png' },
            { name: 'Inoxtag', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Inoxtag-2023.jpg/330px-Inoxtag-2023.jpg' },
            { name: 'Joyca', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Jordan_Rondelli_%28Joyca%29_lors_du_ZEVENT_2025.jpg/330px-Jordan_Rondelli_%28Joyca%29_lors_du_ZEVENT_2025.jpg' },
            // Ajouts
            { name: 'Michou', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Michou_2024.jpg/330px-Michou_2024.jpg' },
            { name: 'Locklear', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Locklear_ZEvent.jpg/330px-Locklear_ZEvent.jpg' },
            { name: 'Doigby', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Doigby_2024.jpg/330px-Doigby_2024.jpg' },
            { name: 'JLTomy', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/JLTomy.jpg/330px-JLTomy.jpg' },
            { name: 'Chowh1', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Chowh1.jpg/330px-Chowh1.jpg' },
        ],
    },
    {
        id: 'nourriture',
        title: 'Le meilleur plat',
        emoji: '🍔',
        items: [
            { name: 'Pizza', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Pizza_Margherita_stu_spivack.jpg/330px-Pizza_Margherita_stu_spivack.jpg' },
            { name: 'Burger', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/RedDot_Burger.jpg/330px-RedDot_Burger.jpg' },
            { name: 'Sushi', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Nigiri_Sushi_%2826478725732%29.jpg/330px-Nigiri_Sushi_%2826478725732%29.jpg' },
            { name: 'Tacos', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg/330px-001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg' },
            { name: 'Pâtes', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Pasta_2006_1.jpg/330px-Pasta_2006_1.jpg' },
            { name: 'Ramen', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Charsiu_ramen_02.jpg/330px-Charsiu_ramen_02.jpg' },
            { name: 'Kebab', img: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/D%C3%B6ner_kebab_slicing.jpg' },
            { name: 'Raclette', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Raclette_20040817_140816.jpg/330px-Raclette_20040817_140816.jpg' },
            { name: 'Frites', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Fries_2.jpg/330px-Fries_2.jpg' },
            { name: 'Poulet rôti', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Max%27s_Roasted_Chicken_-_Evan_Swigart.jpg/330px-Max%27s_Roasted_Chicken_-_Evan_Swigart.jpg' },
            { name: 'Curry', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Indiandishes.jpg/330px-Indiandishes.jpg' },
            { name: 'Croissant', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Croissant-Petr_Kratochvil.jpg/330px-Croissant-Petr_Kratochvil.jpg' },
            // Ajouts
            { name: 'Steak frites', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Steak_with_fries.jpg/330px-Steak_with_fries.jpg' },
            { name: 'Lasagnes', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Lasagne_-_v2.jpg/330px-Lasagne_-_v2.jpg' },
            { name: 'Couscous', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Couscous_with_vegetables.jpg/330px-Couscous_with_vegetables.jpg' },
            { name: 'Magret de canard', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Magret_de_canard.jpg/330px-Magret_de_canard.jpg' },
            { name: 'Fondue savoyarde', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Fondue_savoyarde.jpg/330px-Fondue_savoyarde.jpg' },
        ],
    },
    {
        id: 'bonbons',
        title: 'Le meilleur bonbon',
        emoji: '🍬',
        items: [
            { name: 'Fraise Tagada', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Fraise_Tagada.jpg/330px-Fraise_Tagada.jpg' },
            { name: 'Ours Haribo', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Oursons_g%C3%A9latine_march%C3%A9_Rouffignac.jpg/330px-Oursons_g%C3%A9latine_march%C3%A9_Rouffignac.jpg' },
            { name: 'Carambar', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Jielbeaumadier_carambars_2010.jpg/330px-Jielbeaumadier_carambars_2010.jpg' },
            { name: 'Dragibus', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Liebesperlen.JPG/330px-Liebesperlen.JPG' },
            { name: 'Réglisse', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Liquorice_wheels.jpg/330px-Liquorice_wheels.jpg' },
            { name: 'Sucette', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Farbenfrohe_Lollipops%2C_Austria.jpg/330px-Farbenfrohe_Lollipops%2C_Austria.jpg' },
            { name: 'Guimauve', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/White_Marshmallows.jpg/330px-White_Marshmallows.jpg' },
            { name: 'Chamallow', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Guimauves-figures.jpg/330px-Guimauves-figures.jpg' },
            { name: 'Jelly Bean', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/JellyBellyPile.JPG/330px-JellyBellyPile.JPG' },
            { name: 'Wine Gum', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Maynards-Wine-Gums.jpg/330px-Maynards-Wine-Gums.jpg' },
            // Ajouts
            { name: 'Schtroumpfs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Schtroumpfs_Haribo.jpg/330px-Schtroumpfs_Haribo.jpg' },
            { name: 'Rotella', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Rotella.jpg/330px-Rotella.jpg' },
            { name: 'Malabar', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Malabar_gum.jpg/330px-Malabar_gum.jpg' },
            { name: 'M&M\'s', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/M%26Ms_plain.jpg/330px-M%26Ms_plain.jpg' },
        ],
    },
    {
        id: 'pays',
        title: 'Le plus beau drapeau',
        emoji: '🏳️',
        items: [
            flag('fr', 'France'), flag('jp', 'Japon'), flag('br', 'Brésil'), flag('it', 'Italie'),
            flag('de', 'Allemagne'), flag('es', 'Espagne'), flag('ca', 'Canada'), flag('us', 'États-Unis'),
            flag('kr', 'Corée du Sud'), flag('za', 'Afrique du Sud'), flag('mx', 'Mexique'), flag('se', 'Suède'),
            // Ajouts
            flag('au', 'Australie'), flag('nz', 'Nouvelle-Zélande'), flag('ch', 'Suisse'), flag('pt', 'Portugal'),
            flag('nl', 'Pays-Bas'), flag('in', 'Inde'), flag('tr', 'Turquie'), flag('ar', 'Argentine'),
            flag('cl', 'Chili'), flag('th', 'Thaïlande'), flag('gr', 'Grèce'), flag('ie', 'Irlande'),
            // Ajouts
            flag('be', 'Belgique'), flag('no', 'Norvège'), flag('dk', 'Danemark'), flag('fi', 'Finlande'),
            flag('pl', 'Pologne'), flag('ua', 'Ukraine'), flag('ma', 'Maroc'), flag('sn', 'Sénégal'),
            flag('co', 'Colombie'), flag('pe', 'Pérou'), flag('vn', 'Vietnam'), flag('id', 'Indonésie'),
        ],
    },
    {
        id: 'animaux',
        title: "L'animal préféré",
        emoji: '🐾',
        items: [
            { name: 'Chat', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Cat_August_2010-4.jpg/330px-Cat_August_2010-4.jpg' },
            { name: 'Chien', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Huskiesatrest.jpg/330px-Huskiesatrest.jpg' },
            { name: 'Renard', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg/330px-Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg' },
            { name: 'Panda', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/330px-Grosser_Panda.JPG' },
            { name: 'Loup', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Eurasian_wolf_2.jpg/330px-Eurasian_wolf_2.jpg' },
            { name: 'Lion', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg/330px-020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg' },
            { name: 'Tigre', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Bengal_tiger_%28Panthera_tigris_tigris%29_female_3_crop.jpg/330px-Bengal_tiger_%28Panthera_tigris_tigris%29_female_3_crop.jpg' },
            { name: 'Loutre', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Fischotter%2C_Lutra_Lutra.JPG/330px-Fischotter%2C_Lutra_Lutra.JPG' },
            { name: 'Pingouin', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Aptenodytes_forsteri_-Snow_Hill_Island%2C_Antarctica_-adults_and_juvenile-8.jpg/330px-Aptenodytes_forsteri_-Snow_Hill_Island%2C_Antarctica_-adults_and_juvenile-8.jpg' },
            { name: 'Dauphin', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Tursiops_truncatus_01-cropped.jpg/330px-Tursiops_truncatus_01-cropped.jpg' },
            { name: 'Aigle', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Bald_eagle_about_to_fly_in_Alaska_%282016%29.jpg/330px-Bald_eagle_about_to_fly_in_Alaska_%282016%29.jpg' },
            { name: 'Capybara', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Capybaracropped.jpg/330px-Capybaracropped.jpg' },
            // Ajouts
            { name: 'Koala', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Koala_climbing_tree.jpg/330px-Koala_climbing_tree.jpg' },
            { name: 'Hérisson', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/European_hedgehog.jpg/330px-European_hedgehog.jpg' },
            { name: 'Flamant rose', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Greater_flamingo.jpg/330px-Greater_flamingo.jpg' },
            { name: 'Paresseux', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Bradypus.jpg/330px-Bradypus.jpg' },
        ],
    },
    {
        id: 'marvel',
        title: 'Le meilleur film Marvel',
        emoji: '🦸',
        items: [
            { name: 'Iron Man', img: 'https://upload.wikimedia.org/wikipedia/en/0/02/Iron_Man_%282008_film%29_poster.jpg' },
            { name: 'Avengers', img: 'https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg' },
            { name: 'Endgame', img: 'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg' },
            { name: 'Black Panther', img: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Black_Panther_%28film%29_poster.jpg' },
            { name: 'No Way Home', img: 'https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg' },
            { name: 'Gardiens de la Galaxie', img: 'https://upload.wikimedia.org/wikipedia/en/3/33/Guardians_of_the_Galaxy_%28film%29_poster.jpg' },
            { name: 'Thor: Ragnarok', img: 'https://upload.wikimedia.org/wikipedia/en/7/7d/Thor_Ragnarok_poster.jpg' },
            { name: 'Winter Soldier', img: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Captain_America_The_Winter_Soldier_poster.jpg' },
            { name: 'Doctor Strange', img: 'https://upload.wikimedia.org/wikipedia/en/a/a1/Doctor_Strange_%282016_film%29_poster.jpg' },
            { name: 'Infinity War', img: 'https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg' },
            // Ajouts
            { name: 'Civil War', img: 'https://upload.wikimedia.org/wikipedia/en/5/53/Captain_America_Civil_War_poster.jpg' },
            { name: 'Shang-Chi', img: 'https://upload.wikimedia.org/wikipedia/en/7/74/Shang-Chi_and_the_Legend_of_the_Ten_Rings_poster.jpeg' },
            { name: 'Spider-Man: Homecoming', img: 'https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg' },
            { name: 'Gardiens de la Galaxie Vol. 2', img: 'https://upload.wikimedia.org/wikipedia/en/3/32/Guardians_of_the_Galaxy_Vol._2_poster.jpg' },
            { name: 'Captain Marvel', img: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Captain_Marvel_%28film%29_poster.jpg' },
        ],
    },
    {
        id: 'dc',
        title: 'Le meilleur film DC',
        emoji: '🦇',
        img: 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg',
        items: [
            { name: 'The Dark Knight', img: 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg' },
            { name: 'Joker', img: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg' },
            { name: 'Wonder Woman', img: 'https://upload.wikimedia.org/wikipedia/en/b/b0/Wonder_Woman_%282017_film%29_poster.jpg' },
            { name: 'Aquaman', img: 'https://upload.wikimedia.org/wikipedia/en/e/ed/Aquaman_%28film%29_poster.jpg' },
            { name: 'The Batman', img: 'https://upload.wikimedia.org/wikipedia/en/f/ff/The_Batman_%28film%29_poster.jpg' },
            { name: 'Man of Steel', img: 'https://upload.wikimedia.org/wikipedia/en/5/50/Man_of_Steel_%28film%29_poster.jpg' },
            // Ajouts
            { name: 'Batman Begins', img: 'https://upload.wikimedia.org/wikipedia/en/a/af/Batman_Begins_Poster.jpg' },
            { name: 'The Suicide Squad', img: 'https://upload.wikimedia.org/wikipedia/en/6/6f/Suicide_Squad.png' },
            { name: 'Shazam!', img: 'https://upload.wikimedia.org/wikipedia/en/c/c2/Shazam%21_%28film%29_poster.jpg' },
            { name: 'Justice League', img: 'https://upload.wikimedia.org/wikipedia/en/6/6b/Justice_League_%28film%29_poster.jpg' },
            { name: 'Black Adam', img: 'https://upload.wikimedia.org/wikipedia/en/a/a9/Black_Adam_%28film%29_poster.jpg' },
            { name: 'The Flash', img: 'https://upload.wikimedia.org/wikipedia/en/e/ed/The_Flash_%28film%29_poster.jpg' },
            { name: 'Birds of Prey', img: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Birds_of_Prey_%282020_film%29_poster.jpg' },
            { name: 'Superman (2025)', img: 'https://upload.wikimedia.org/wikipedia/en/3/32/Superman_%282025_film%29_poster.jpg' },
        ],
    },
    {
        id: 'starwars',
        title: 'Le meilleur de Star Wars',
        emoji: '🌌',
        img: 'https://upload.wikimedia.org/wikipedia/en/3/3f/The_Empire_Strikes_Back_%281980_film%29.jpg',
        items: [
            { name: 'L\'Empire contre-attaque', img: 'https://upload.wikimedia.org/wikipedia/en/3/3f/The_Empire_Strikes_Back_%281980_film%29.jpg' },
            { name: 'Un Nouvel Espoir', img: 'https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg' },
            { name: 'Le Retour du Jedi', img: 'https://upload.wikimedia.org/wikipedia/en/b/b2/ReturnOfTheJediPoster1983.jpg' },
            { name: 'Rogue One', img: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Rogue_One%2C_A_Star_Wars_Story_poster.png' },
            { name: 'Andor', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Andor.svg/960px-Andor.svg.png' },
            { name: 'The Mandalorian', img: 'https://upload.wikimedia.org/wikipedia/en/0/04/The_Mandalorian_season_1_poster.jpg' },
            // Ajouts : préquelles + postlogie + spin-off
            { name: 'La Menace fantôme', img: 'https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg' },
            { name: 'L\'Attaque des clones', img: 'https://upload.wikimedia.org/wikipedia/en/3/32/Star_Wars_-_Episode_II_Attack_of_the_Clones_%28movie_poster%29.jpg' },
            { name: 'La Revanche des Sith', img: 'https://upload.wikimedia.org/wikipedia/en/9/93/Star_Wars_Episode_III_Revenge_of_the_Sith_poster.jpg' },
            { name: 'Le Réveil de la Force', img: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Star_Wars_The_Force_Awakens_Theatrical_Poster.jpg' },
            { name: 'Les Derniers Jedi', img: 'https://upload.wikimedia.org/wikipedia/en/7/7f/Star_Wars_The_Last_Jedi.jpg' },
            { name: 'L\'Ascension de Skywalker', img: 'https://upload.wikimedia.org/wikipedia/en/a/af/Star_Wars_The_Rise_of_Skywalker_poster.jpg' },
            { name: 'Solo', img: 'https://upload.wikimedia.org/wikipedia/en/5/54/Solo_A_Star_Wars_Story_poster.jpg' },
        ],
    },
    {
        id: 'jeuxvideo',
        title: 'Le meilleur jeu vidéo',
        emoji: '🎮',
        img: 'https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg',
        items: [
            { name: 'The Legend of Zelda: BOTW', img: 'https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg' },
            { name: 'Elden Ring', img: 'https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg' },
            { name: 'Minecraft', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Minecraft-creeper-face.svg/500px-Minecraft-creeper-face.svg.png' },
            { name: 'GTA V', img: 'https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png' },
            { name: 'The Witcher 3', img: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg' },
            { name: 'Super Mario Odyssey', img: 'https://upload.wikimedia.org/wikipedia/en/8/8d/Super_Mario_Odyssey.jpg' },
            { name: 'Red Dead Redemption 2', img: 'https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg' },
            { name: 'Hades', img: 'https://upload.wikimedia.org/wikipedia/en/c/cc/Hades_cover_art.jpg' },
            // Ajouts
            { name: 'God of War', img: 'https://upload.wikimedia.org/wikipedia/en/a/a7/God_of_War_4_cover.jpg' },
            { name: 'The Last of Us Part II', img: 'https://upload.wikimedia.org/wikipedia/en/4/4f/TLOU_P2_Box_Art_2.png' },
            { name: 'Dark Souls III', img: 'https://upload.wikimedia.org/wikipedia/en/b/bb/Dark_souls_3_cover_art.jpg' },
            { name: 'Cyberpunk 2077', img: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg' },
            { name: 'Animal Crossing: New Horizons', img: 'https://upload.wikimedia.org/wikipedia/en/1/1f/Animal_Crossing_New_Horizons.jpg' },
            { name: 'Portal 2', img: 'https://upload.wikimedia.org/wikipedia/en/f/f9/Portal2cover.jpg' },
            { name: 'Sekiro', img: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Sekiro_art.jpg' },
            { name: 'Mario Kart 8', img: 'https://upload.wikimedia.org/wikipedia/en/b/b5/MarioKart8Boxart.jpg' },
        ],
    },
    {
        id: 'boissons',
        title: 'La meilleure boisson',
        emoji: '🥤',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Coca_Cola_Flasche_-_Original_Taste.jpg/330px-Coca_Cola_Flasche_-_Original_Taste.jpg',
        items: [
            { name: 'Coca-Cola', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Coca_Cola_Flasche_-_Original_Taste.jpg/330px-Coca_Cola_Flasche_-_Original_Taste.jpg' },
            { name: 'Café', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Latte_and_dark_coffee.jpg/330px-Latte_and_dark_coffee.jpg' },
            { name: 'Thé', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Longjing_tea_steeping_in_gaiwan.jpg/330px-Longjing_tea_steeping_in_gaiwan.jpg' },
            { name: 'Chocolat chaud', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/After_The_St._Patrick%27s_Parade_Late_Lunch_%40_Lemon%2C_Dawson_Street%2C_Dublin%2C_Rep._Of_Ireland_A_Fine_Tradition%21_%286992614913%29.jpg/330px-After_The_St._Patrick%27s_Parade_Late_Lunch_%40_Lemon%2C_Dawson_Street%2C_Dublin%2C_Rep._Of_Ireland_A_Fine_Tradition%21_%286992614913%29.jpg' },
            { name: 'Jus d\'orange', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Orangejuice.jpg/330px-Orangejuice.jpg' },
            { name: 'Bières artisanales', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Hacker-Pschorr_Oktoberfest_Girl_Remix.jpg/330px-Hacker-Pschorr_Oktoberfest_Girl_Remix.jpg' },
            { name: 'Limonade', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Lemonade_-_27682817724.jpg/330px-Lemonade_-_27682817724.jpg' },
            // Ajouts
            { name: 'Fanta', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fanta_2023.svg/330px-Fanta_2023.svg.png' },
            { name: 'Sprite', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Sprite_lemon_lime_1.jpg/330px-Sprite_lemon_lime_1.jpg' },
            { name: 'Pepsi', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Pepsi_2023.svg/330px-Pepsi_2023.svg.png' },
            { name: 'Red Bull', img: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/RedBullEnergyDrink.svg/330px-RedBullEnergyDrink.svg.png' },
            { name: 'Ice Tea', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Iced_Tea_from_flickr.jpg/330px-Iced_Tea_from_flickr.jpg' },
            { name: 'Milkshake', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Strawberry_milk_shake_%28cropped%29.jpg/330px-Strawberry_milk_shake_%28cropped%29.jpg' },
            { name: 'Mojito', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/15-09-26-RalfR-WLC-0072.jpg/330px-15-09-26-RalfR-WLC-0072.jpg' },
            { name: 'Champagne', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Glass_of_champagne.jpg/330px-Glass_of_champagne.jpg' },
        ],
    },
    {
        id: 'desserts',
        title: 'Le meilleur dessert',
        emoji: '🍰',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Tiramisu_-_Raffaele_Diomede.jpg/330px-Tiramisu_-_Raffaele_Diomede.jpg',
        items: [
            { name: 'Crème brûlée', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/2014_0531_Cr%C3%A8me_br%C3%BBl%C3%A9e_Doi_Mae_Salong_%28cropped%29.jpg/330px-2014_0531_Cr%C3%A8me_br%C3%BBl%C3%A9e_Doi_Mae_Salong_%28cropped%29.jpg' },
            { name: 'Tiramisu', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Tiramisu_-_Raffaele_Diomede.jpg/330px-Tiramisu_-_Raffaele_Diomede.jpg' },
            { name: 'Macarons', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/VanillaMacaron.jpg/330px-VanillaMacaron.jpg' },
            { name: 'Éclair', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Two_Safeway_Chocolate_Eclairs_%2819043880936%29.jpg/330px-Two_Safeway_Chocolate_Eclairs_%2819043880936%29.jpg' },
            { name: 'Fondant au chocolat', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Chocolate_Fondant.jpg/330px-Chocolate_Fondant.jpg' },
            { name: 'Cheesecake', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Baked_cheesecake_with_raspberries_and_blueberries.jpg/330px-Baked_cheesecake_with_raspberries_and_blueberries.jpg' },
            // Ajouts
            { name: 'Profiterole', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Profiterole_choc.jpg/330px-Profiterole_choc.jpg' },
            { name: 'Cookie', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Choco_chip_cookie.png/330px-Choco_chip_cookie.png' },
            { name: 'Panna cotta', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Panna_Cotta_with_cream_and_garnish.jpg/330px-Panna_Cotta_with_cream_and_garnish.jpg' },
            { name: 'Gaufre', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Waffles_with_Strawberries.jpg/330px-Waffles_with_Strawberries.jpg' },
            { name: 'Crêpe', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Crepes_dsc07085.jpg/330px-Crepes_dsc07085.jpg' },
            { name: 'Donut', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glazed-Donut.jpg/330px-Glazed-Donut.jpg' },
            { name: 'Tarte aux pommes', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Lattice_apple_pie.png/330px-Lattice_apple_pie.png' },
            { name: 'Banoffee', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Banoffeepie.jpg/330px-Banoffeepie.jpg' },
            { name: 'Mille-feuille', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Mille-feuille_fran%C3%A7ais_1.jpg/330px-Mille-feuille_fran%C3%A7ais_1.jpg' },
        ],
    },
    {
        id: 'kpop',
        title: 'Le meilleur groupe/artiste K-pop',
        emoji: '🎤',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/BTS_during_a_White_House_press_conference_May_31%2C_2022_%28cropped%29.jpg/330px-BTS_during_a_White_House_press_conference_May_31%2C_2022_%28cropped%29.jpg',
        items: [
            { name: 'BTS', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/BTS_during_a_White_House_press_conference_May_31%2C_2022_%28cropped%29.jpg/330px-BTS_during_a_White_House_press_conference_May_31%2C_2022_%28cropped%29.jpg' },
            { name: 'Blackpink', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/20240809_Blackpink_Pink_Carpet_09.png/330px-20240809_Blackpink_Pink_Carpet_09.png' },
            { name: 'Stray Kids', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Stray_Kids_at_the_40th_Golden_Disc_Awards%2C_January_10%2C_2026_%281%29.png/330px-Stray_Kids_at_the_40th_Golden_Disc_Awards%2C_January_10%2C_2026_%281%29.png' },
            { name: 'NewJeans', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/NewJeans_2023_MelonMusicAwards_composite.jpg/330px-NewJeans_2023_MelonMusicAwards_composite.jpg' },
            { name: 'Twice', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Twice_-_Dickies_Arena%2C_2022_%28cropped%29.jpg/330px-Twice_-_Dickies_Arena%2C_2022_%28cropped%29.jpg' },
            // Ajouts
            { name: 'Red Velvet', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/%EB%A0%88%EB%93%9C%EB%B2%A8%EB%B2%B3%28Red_Velvet%29_%EC%BC%80%EC%9D%B4%EC%BD%98_%EC%9E%AC%ED%8C%AC_2024_%EB%A0%88%EB%93%9C%EC%B9%B4%ED%8E%AB_KCON_JAPAN_2024_%281%29.jpg/330px-%EB%A0%88%EB%93%9C%EB%B2%A8%EB%B2%B3%28Red_Velvet%29_%EC%BC%80%EC%9D%B4%EC%BD%98_%EC%9E%AC%ED%8C%AC_2024_%EB%A0%88%EB%93%9C%EC%B9%B4%ED%8E%AB_KCON_JAPAN_2024_%281%29.jpg' },
            { name: 'IVE', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Ive_at_the_40th_Golden_Disc_Awards%2C_January_10%2C_2026_%282%29.png/330px-Ive_at_the_40th_Golden_Disc_Awards%2C_January_10%2C_2026_%282%29.png' },
            { name: '(G)I-dle', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/I-dle_at_Love_Your_W_on_October_15%2C_2025.png/330px-I-dle_at_Love_Your_W_on_October_15%2C_2025.png' },
        ],
    },
    {
        id: 'footballeurs',
        title: 'Le meilleur footballeur',
        emoji: '⚽',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Lionel_Messi_20180626.jpg/330px-Lionel_Messi_20180626.jpg',
        items: [
            { name: 'Lionel Messi', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Lionel_Messi_20180626.jpg/330px-Lionel_Messi_20180626.jpg' },
            { name: 'Cristiano Ronaldo', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cristiano_Ronaldo_2018.jpg/330px-Cristiano_Ronaldo_2018.jpg' },
            { name: 'Kylian Mbappé', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Picture_with_Mbapp%C3%A9_%28cropped%29_%28cropped%29.jpg/330px-Picture_with_Mbapp%C3%A9_%28cropped%29_%28cropped%29.jpg' },
            { name: 'Zinédine Zidane', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg/330px-Zinedine_Zidane_by_Tasnim_03.jpg' },
            { name: 'Erling Haaland', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Erling_Haaland_June_2025.jpg/330px-Erling_Haaland_June_2025.jpg' },
            { name: 'Kevin De Bruyne', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg/330px-Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg' },
            { name: 'Karim Benzema', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Karim_Benzema_wearing_Real_Madrid_home_kit_2021-2022.jpg/330px-Karim_Benzema_wearing_Real_Madrid_home_kit_2021-2022.jpg' },
            { name: 'Neymar', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg/330px-Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg' },
        ],
    },
    {
        id: 'animation',
        title: 'Le meilleur film d\'animation',
        emoji: '🎬',
        img: 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg',
        items: [
            { name: 'Le Roi Lion', img: 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg' },
            { name: 'Toy Story', img: 'https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg' },
            { name: 'Vice-Versa', img: 'https://upload.wikimedia.org/wikipedia/en/0/0a/Inside_Out_%282015_film%29_poster.jpg' },
            { name: 'Là-haut', img: 'https://upload.wikimedia.org/wikipedia/en/0/05/Up_%282009_film%29.jpg' },
            { name: 'Spider-Man: New Generation', img: 'https://upload.wikimedia.org/wikipedia/en/f/fa/Spider-Man_Into_the_Spider-Verse_poster.png' },
            { name: 'Shrek', img: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Shrek_%282001_animated_feature_film%29.jpg' },
            { name: 'Le Voyage de Chihiro', img: 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png' },
            { name: 'Coco', img: 'https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg' },
        ],
    },
    {
        id: 'monuments',
        title: 'Le plus beau monument',
        emoji: '🏛️',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/330px-Tour_Eiffel_Wikimedia_Commons.jpg',
        items: [
            { name: 'Tour Eiffel', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/330px-Tour_Eiffel_Wikimedia_Commons.jpg' },
            { name: 'Colisée', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/330px-Colosseo_2020.jpg' },
            { name: 'Taj Mahal', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Taj_Mahal%2C_Agra%2C_India_edit3.jpg/330px-Taj_Mahal%2C_Agra%2C_India_edit3.jpg' },
            { name: 'Statue de la Liberté', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Front_view_of_Statue_of_Liberty_with_pedestal_and_base_2024.jpg/330px-Front_view_of_Statue_of_Liberty_with_pedestal_and_base_2024.jpg' },
            { name: 'Big Ben', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Houses_of_Parliament_in_2022_%28cropped%29.jpg/330px-Houses_of_Parliament_in_2022_%28cropped%29.jpg' },
            { name: 'Sagrada Família', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/SF_maig_2026.jpg/330px-SF_maig_2026.jpg' },
            { name: 'Machu Picchu', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Before_Machu_Picchu.jpg/330px-Before_Machu_Picchu.jpg' },
            { name: 'Pyramides de Gizeh', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/330px-All_Gizah_Pyramids.jpg' },
        ],
    },
    {
        id: 'voitures',
        title: 'La plus belle voiture',
        emoji: '🏎️',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/2018_Ferrari_488_GTB_4.jpg/330px-2018_Ferrari_488_GTB_4.jpg',
        items: [
            { name: 'Ferrari 488', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/2018_Ferrari_488_GTB_4.jpg/330px-2018_Ferrari_488_GTB_4.jpg' },
            { name: 'Lamborghini Huracán', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/2017_Lamborghini_Huracan_LP610.jpg/330px-2017_Lamborghini_Huracan_LP610.jpg' },
            { name: 'Porsche 911', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/2025_Porsche_992_Carrera_convertible_DSC_7026.jpg/330px-2025_Porsche_992_Carrera_convertible_DSC_7026.jpg' },
            { name: 'Bugatti Veyron', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Bugatti_Veyron_16.4_%E2%80%93_Frontansicht_%281%29%2C_5._April_2012%2C_D%C3%BCsseldorf.jpg/330px-Bugatti_Veyron_16.4_%E2%80%93_Frontansicht_%281%29%2C_5._April_2012%2C_D%C3%BCsseldorf.jpg' },
            { name: 'McLaren P1', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/McLaren_P1.jpg/330px-McLaren_P1.jpg' },
            { name: 'Aston Martin DB11', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/2018_Aston_Martin_DB11_V8_Automatic_4.0_Front.jpg/330px-2018_Aston_Martin_DB11_V8_Automatic_4.0_Front.jpg' },
            { name: 'Nissan GT-R', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/2009-2010_Nissan_GT-R_%28R35%29_coupe_01.jpg/330px-2009-2010_Nissan_GT-R_%28R35%29_coupe_01.jpg' },
            { name: 'Tesla Model S', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Tesla_Model_S_%28Facelift_ab_04-2016%29_%28cropped%29.jpg/330px-Tesla_Model_S_%28Facelift_ab_04-2016%29_%28cropped%29.jpg' },
            { name: 'Ford Mustang', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Ford_Mustang_VII_GT_Rutesheimer_Autoschau_2025_DSC_9234.jpg/330px-Ford_Mustang_VII_GT_Rutesheimer_Autoschau_2025_DSC_9234.jpg' },
            { name: 'Chevrolet Corvette', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/2021_Chevrolet_Corvette_C8.jpg/330px-2021_Chevrolet_Corvette_C8.jpg' },
            { name: 'Dodge Challenger', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Dodge_Challenger_SRT8_%282015%29_Hirschaid-20220709-RM-120221_%28cropped%29.jpg/330px-Dodge_Challenger_SRT8_%282015%29_Hirschaid-20220709-RM-120221_%28cropped%29.jpg' },
            { name: 'BMW M3', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/BMW_M3_Competition_%28G80%29_IMG_4041.jpg/330px-BMW_M3_Competition_%28G80%29_IMG_4041.jpg' },
        ],
    },
    {
        id: 'villes',
        title: 'La plus belle ville',
        emoji: '🌆',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg/330px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg',
        items: [
            { name: 'Paris', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg/330px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg' },
            { name: 'Tokyo', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Tokyo_Montage_2015.jpg/330px-Tokyo_Montage_2015.jpg' },
            { name: 'New York', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg/330px-View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg' },
            { name: 'Londres', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/London_Skyline_%28125508655%29.jpeg/330px-London_Skyline_%28125508655%29.jpeg' },
            { name: 'Rome', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Collage_Rome.jpg/330px-Collage_Rome.jpg' },
            { name: 'Barcelone', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Aerial_view_of_Barcelona%2C_Spain_%2851227309370%29_edited.jpg/330px-Aerial_view_of_Barcelona%2C_Spain_%2851227309370%29_edited.jpg' },
            { name: 'Venise', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Collage_Venezia.jpg/330px-Collage_Venezia.jpg' },
            { name: 'Istanbul', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Istanbul_collage_4.jpg/330px-Istanbul_collage_4.jpg' },
            { name: 'Sydney', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Sydney_Opera_House_and_Harbour_Bridge_Dusk_%282%29_2019-06-21.jpg/330px-Sydney_Opera_House_and_Harbour_Bridge_Dusk_%282%29_2019-06-21.jpg' },
            { name: 'Dubaï', img: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Burj_Khalifa_2021.jpg/330px-Burj_Khalifa_2021.jpg' },
            { name: 'Rio de Janeiro', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Cidade_Maravilhosa.jpg/330px-Cidade_Maravilhosa.jpg' },
        ],
    },
    {
        id: 'series',
        title: 'La meilleure série TV',
        emoji: '📺',
        img: 'https://image.tmdb.org/t/p/w500/hVVxgGZFR3JaXmkstnG1IR9Qbt6.jpg',
        items: [
            { name: 'Breaking Bad', img: 'https://image.tmdb.org/t/p/w500/hVVxgGZFR3JaXmkstnG1IR9Qbt6.jpg' },
            { name: 'Game of Thrones', img: 'https://image.tmdb.org/t/p/w500/eRMfekBOnwyE9G0ffyEJIBOjX2n.jpg' },
            { name: 'Stranger Things', img: 'https://image.tmdb.org/t/p/w500/iGZkjG3BDTuWsWu9Cdmh2jh3q7d.jpg' },
            { name: 'The Last of Us', img: 'https://image.tmdb.org/t/p/w500/4pMd9VAdqm96KA2W4X8yetgc7EF.jpg' },
            { name: 'The Office', img: 'https://image.tmdb.org/t/p/w500/2dApsoX4bd98szjrbj5i3syYOh2.jpg' },
            { name: 'Friends', img: 'https://image.tmdb.org/t/p/w500/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg' },
            { name: 'Peaky Blinders', img: 'https://image.tmdb.org/t/p/w500/wfD5hDb61sS203D0te7JbIzeyQe.jpg' },
            { name: 'La Casa de Papel', img: 'https://image.tmdb.org/t/p/w500/u5Ye3LqV5LqTGjLqtkTCkA4m63W.jpg' },
            { name: 'The Witcher', img: 'https://image.tmdb.org/t/p/w500/rhErSlk0M236rNFertVAZa9lz9S.jpg' },
            { name: 'Wednesday', img: 'https://image.tmdb.org/t/p/w500/1UzED7WZJgzEIeVz1xiuZ1529nb.jpg' },
            { name: 'Dark', img: 'https://image.tmdb.org/t/p/w500/vbG0zu0lIVDZZaUVOZuBIE9kno3.jpg' },
            { name: 'Lupin', img: 'https://image.tmdb.org/t/p/w500/sOUWRai0215iUSMackrZx3Y1j05.jpg' },
            { name: 'The Walking Dead', img: 'https://image.tmdb.org/t/p/w500/cVDzRylKifHGS1PFNlePfJ8sxUj.jpg' },
            { name: 'Squid Game', img: 'https://image.tmdb.org/t/p/w500/heV89pC6pv5fz1plikfyQxYuE4L.jpg' },
            { name: 'Chernobyl', img: 'https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg' },
            { name: 'The Wire', img: 'https://image.tmdb.org/t/p/w500/efV8dprxpU1JXNGqepVY68ZaHKZ.jpg' },
        ],
    },
    {
        id: 'drapeaux-monde',
        title: 'Le plus beau drapeau du monde',
        emoji: '🌍',
        items: [
            flag('fr', 'France'), flag('de', 'Allemagne'), flag('it', 'Italie'), flag('es', 'Espagne'),
            flag('pt', 'Portugal'), flag('gb', 'Royaume-Uni'), flag('ie', 'Irlande'), flag('nl', 'Pays-Bas'),
            flag('be', 'Belgique'), flag('ch', 'Suisse'), flag('at', 'Autriche'), flag('se', 'Suède'),
            flag('no', 'Norvège'), flag('dk', 'Danemark'), flag('fi', 'Finlande'), flag('is', 'Islande'),
            flag('pl', 'Pologne'), flag('cz', 'Tchéquie'), flag('hu', 'Hongrie'), flag('ro', 'Roumanie'),
            flag('gr', 'Grèce'), flag('tr', 'Turquie'), flag('ua', 'Ukraine'), flag('ru', 'Russie'),
            flag('us', 'États-Unis'), flag('ca', 'Canada'), flag('mx', 'Mexique'), flag('br', 'Brésil'),
            flag('ar', 'Argentine'), flag('cl', 'Chili'), flag('co', 'Colombie'), flag('pe', 'Pérou'),
            flag('jp', 'Japon'), flag('kr', 'Corée du Sud'), flag('cn', 'Chine'), flag('in', 'Inde'),
            flag('th', 'Thaïlande'), flag('vn', 'Vietnam'), flag('id', 'Indonésie'), flag('ph', 'Philippines'),
            flag('au', 'Australie'), flag('nz', 'Nouvelle-Zélande'), flag('za', 'Afrique du Sud'), flag('ng', 'Nigeria'),
            flag('eg', 'Égypte'), flag('ma', 'Maroc'), flag('sn', 'Sénégal'), flag('ke', 'Kenya'),
            flag('sa', 'Arabie saoudite'), flag('qa', 'Qatar'),
        ],
    },
    {
        id: 'pokemon-legendaire',
        title: 'Le meilleur Pokémon légendaire',
        emoji: '✨',
        items: [
            poke(144, 'Artikodin'), poke(145, 'Électhor'), poke(146, 'Sulfura'), poke(150, 'Mewtwo'),
            poke(151, 'Mew'), poke(243, 'Raikou'), poke(244, 'Entei'), poke(245, 'Suicune'),
            poke(249, 'Lugia'), poke(250, 'Ho-Oh'), poke(251, 'Celebi'), poke(377, 'Regirock'),
            poke(378, 'Regice'), poke(379, 'Registeel'), poke(380, 'Latias'), poke(381, 'Latios'),
            poke(382, 'Kyogre'), poke(383, 'Groudon'), poke(384, 'Rayquaza'), poke(385, 'Jirachi'),
            poke(386, 'Deoxys'), poke(483, 'Dialga'), poke(484, 'Palkia'), poke(487, 'Giratina'),
            poke(491, 'Darkrai'), poke(493, 'Arceus'), poke(643, 'Reshiram'), poke(644, 'Zekrom'),
            poke(646, 'Kyurem'), poke(716, 'Xerneas'), poke(717, 'Yveltal'), poke(800, 'Necrozma'),
            poke(888, 'Zacian'), poke(889, 'Zamazenta'), poke(890, 'Éthernatos'),
        ],
    },
    {
        id: 'catch',
        title: 'Le meilleur catcheur (WWE)',
        emoji: '🤼',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/John_Cena_by_Gage_Skidmore.jpg/330px-John_Cena_by_Gage_Skidmore.jpg',
        items: [
            { name: 'John Cena', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/John_Cena_by_Gage_Skidmore.jpg/330px-John_Cena_by_Gage_Skidmore.jpg' },
            { name: 'The Rock', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Dwayne_Johnson-1764_%284x5_cropped_with_moderate_headroom%29.jpg/330px-Dwayne_Johnson-1764_%284x5_cropped_with_moderate_headroom%29.jpg' },
            { name: 'Stone Cold Steve Austin', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Stone_Cold_Steve_Austin_2016-03-31_%28cropped%29.jpg/330px-Stone_Cold_Steve_Austin_2016-03-31_%28cropped%29.jpg' },
            { name: 'The Undertaker', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/The_Undertaker_US_Marine_Visit_2019_%28cropped%292.jpg/330px-The_Undertaker_US_Marine_Visit_2019_%28cropped%292.jpg' },
            { name: 'Triple H', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/P20250731DT-0076_Paul_Levesque_2025.jpg/330px-P20250731DT-0076_Paul_Levesque_2025.jpg' },
            { name: 'Hulk Hogan', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Hulk_Hogan%2C_circa_1985.jpg/330px-Hulk_Hogan%2C_circa_1985.jpg' },
            { name: 'Randy Orton', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Randy_Orton_RR24_%28cropped%29.jpg/330px-Randy_Orton_RR24_%28cropped%29.jpg' },
            { name: 'Roman Reigns', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Roman_Reigns_RR25_%281%29_%28headshot%29.jpg/330px-Roman_Reigns_RR25_%281%29_%28headshot%29.jpg' },
            { name: 'Seth Rollins', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Seth_Rollins_July_2019.jpg/330px-Seth_Rollins_July_2019.jpg' },
            { name: 'Brock Lesnar', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Brock_Lesnar_At_SummerSlam_2023_%28cropped%29.jpg/330px-Brock_Lesnar_At_SummerSlam_2023_%28cropped%29.jpg' },
            { name: 'Rey Mysterio', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Rey_Mysterio_%2829081123617%29.jpg/330px-Rey_Mysterio_%2829081123617%29.jpg' },
            { name: 'Edge', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Adam_Copeland_by_Gage_Skidmore.jpg/330px-Adam_Copeland_by_Gage_Skidmore.jpg' },
            { name: 'CM Punk', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/CM_Punk_WWE_2024_%28close_crop%29.png/330px-CM_Punk_WWE_2024_%28close_crop%29.png' },
            { name: 'Batista', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Dave_Bautista_Photo_Op_GalaxyCon_Minneapolis_2019.jpg/330px-Dave_Bautista_Photo_Op_GalaxyCon_Minneapolis_2019.jpg' },
            { name: 'Shawn Michaels', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Shawn_Michaels_%2830045287538%29.jpg/330px-Shawn_Michaels_%2830045287538%29.jpg' },
            { name: 'Bret Hart', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bret_Hart_Photo_Op_GalaxyCon_Raleigh_2023.jpg/330px-Bret_Hart_Photo_Op_GalaxyCon_Raleigh_2023.jpg' },
            { name: 'AJ Styles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/AJ_Styles_RR24_%281%29_%28cropped%29.jpg/330px-AJ_Styles_RR24_%281%29_%28cropped%29.jpg' },
            { name: 'Cody Rhodes', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Cody_Rhodes_Fort_Bragg_Army_250_Birthday_Celebration_%28headshot%29.jpg/330px-Cody_Rhodes_Fort_Bragg_Army_250_Birthday_Celebration_%28headshot%29.jpg' },
            { name: 'Becky Lynch', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Becky_Lynch_Galaxycon.jpg/330px-Becky_Lynch_Galaxycon.jpg' },
            { name: 'Kane', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Glenn_Jacobs_%2854185909259%29_%28cropped%29.jpg/330px-Glenn_Jacobs_%2854185909259%29_%28cropped%29.jpg' },
        ],
    },
    {
        id: 'ufc',
        title: 'Le meilleur combattant UFC',
        emoji: '🥋',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Conor_McGregor_2025.jpeg/330px-Conor_McGregor_2025.jpeg',
        items: [
            { name: 'Conor McGregor', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Conor_McGregor_2025.jpeg/330px-Conor_McGregor_2025.jpeg' },
            { name: 'Jon Jones', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Jon_Jones_-_Supporting_Brain_Health_Study.jpg/330px-Jon_Jones_-_Supporting_Brain_Health_Study.jpg' },
            { name: 'Anderson Silva', img: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Anderson_Silva.png' },
            { name: 'Dustin Poirier', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Dustin_Poirier_UFC_269.jpg/330px-Dustin_Poirier_UFC_269.jpg' },
            { name: 'Charles Oliveira', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Charles_Oliveira_do_Bronxs.jpg/330px-Charles_Oliveira_do_Bronxs.jpg' },
            { name: 'Alex Pereira', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Alex_Pereira_in_the_Oval_Office_%28while_President_Donald_J._Trump_is_holding_a_meeting_with_UFC_fighters%29.jpg/330px-Alex_Pereira_in_the_Oval_Office_%28while_President_Donald_J._Trump_is_holding_a_meeting_with_UFC_fighters%29.jpg' },
            { name: 'Francis Ngannou', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Francis_Ngannou_2023_%28cropped%29.png/330px-Francis_Ngannou_2023_%28cropped%29.png' },
            { name: 'Amanda Nunes', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Ceremonial_weigh_ins_-_Amanda_Nunes_vs_Julianna_Pe%C3%B1a_UFC_269_%28cropped%29.jpg/330px-Ceremonial_weigh_ins_-_Amanda_Nunes_vs_Julianna_Pe%C3%B1a_UFC_269_%28cropped%29.jpg' },
            { name: 'Justin Gaethje', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/UFC_Freedom_250%2C_the_mixed_martial_arts_event_produced_by_the_Ultimate_Fighting_Championship%2C_Sunday%2C_June_14%2C_2026%2C_in_the_Grand_Foyer_of_the_White_House_-_67%28cropped%29.jpg/330px-thumbnail.jpg' },
            { name: 'Kamaru Usman', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/KamaruUsmanPress2018.png/330px-KamaruUsmanPress2018.png' },
            { name: 'Khabib Nurmagomedov', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Khabib_nurmagomedov.jpg/330px-Khabib_nurmagomedov.jpg' },
            { name: 'Israel Adesanya', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Israel_Adesanya_at_UFC_230.jpg/330px-Israel_Adesanya_at_UFC_230.jpg' },
            { name: 'Georges St-Pierre', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/2021_-_Centre_Stage_DG4_5765_%2851654942080%29_%28cropped%29.jpg/330px-2021_-_Centre_Stage_DG4_5765_%2851654942080%29_%28cropped%29.jpg' },
            { name: 'Khamzat Chimaev', img: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Khamzat_Chimaev_2022_%28cropped%29.png' },
            { name: 'Islam Makhachev', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Islam_Makhachev_and_Sergey_Melikov_2025_%28cropped%29.jpg/330px-Islam_Makhachev_and_Sergey_Melikov_2025_%28cropped%29.jpg' },
            { name: 'Max Holloway', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Blue_Angels%27_VIP_Rider_Max_Holloway_%281%29_%28cropped%29.jpg/330px-Blue_Angels%27_VIP_Rider_Max_Holloway_%281%29_%28cropped%29.jpg' },
            { name: 'Stipe Miocic', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Stipe_Miocic_%2848086643396%29_%28cropped%29.jpg/330px-Stipe_Miocic_%2848086643396%29_%28cropped%29.jpg' },
            { name: 'Ronda Rousey', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Rousey_HOF_2018_%28cropped%29.jpg/330px-Rousey_HOF_2018_%28cropped%29.jpg' },
            { name: 'Nate Diaz', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Nate_Diaz_Oct_2019.jpg/330px-Nate_Diaz_Oct_2019.jpg' },
        ],
    },
    {
        id: 'boxe',
        title: 'Le meilleur boxeur',
        emoji: '🥊',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Muhammad_Ali_NYWTS.jpg/330px-Muhammad_Ali_NYWTS.jpg',
        items: [
            { name: 'Mohamed Ali', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Muhammad_Ali_NYWTS.jpg/330px-Muhammad_Ali_NYWTS.jpg' },
            { name: 'Mike Tyson', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Mike_Tyson_Photo_Op_GalaxyCon_Austin_2023.jpg/330px-Mike_Tyson_Photo_Op_GalaxyCon_Austin_2023.jpg' },
            { name: 'Floyd Mayweather', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Floyd_Mayweather_Jr_2011.jpg/330px-Floyd_Mayweather_Jr_2011.jpg' },
            { name: 'Tyson Fury', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Tyson_Fury_at_Place_Bell%2C_Laval_Quebec%2C_Canada_-_Dec_16_2017_%28cropped%29.jpg/330px-Tyson_Fury_at_Place_Bell%2C_Laval_Quebec%2C_Canada_-_Dec_16_2017_%28cropped%29.jpg' },
            { name: 'Anthony Joshua', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Anthony_Joshua_2017.png/330px-Anthony_Joshua_2017.png' },
            { name: 'George Foreman', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/George_Foreman_%281973%29.jpg/330px-George_Foreman_%281973%29.jpg' },
            { name: 'Oscar De La Hoya', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Oscar_de_la_Hoya_2014_%28cropped%29.jpg/330px-Oscar_de_la_Hoya_2014_%28cropped%29.jpg' },
            { name: 'Lennox Lewis', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Lenox_Lewis_2010_cropped.jpg/330px-Lenox_Lewis_2010_cropped.jpg' },
            { name: 'Evander Holyfield', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Evander_Holyfield_LA_2011.jpg/330px-Evander_Holyfield_LA_2011.jpg' },
            { name: 'Roy Jones Jr.', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Rou_Jones_Jr._%28cropped%29.jpg/330px-Rou_Jones_Jr._%28cropped%29.jpg' },
            { name: 'Larry Holmes', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Larry_Holmes_1996.jpg/330px-Larry_Holmes_1996.jpg' },
        ],
    },
    {
        id: 'f1',
        title: 'Le meilleur pilote de F1',
        emoji: '🏁',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg/330px-Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg',
        items: [
            { name: 'Lewis Hamilton', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg/330px-Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg' },
            { name: 'Max Verstappen', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3973_by_Stepro_%28medium_crop%29.jpg/330px-2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3973_by_Stepro_%28medium_crop%29.jpg' },
            { name: 'Michael Schumacher', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/A%C3%A9cio_Neves%2C_Michael_Schumacher_e_Didi_%28Cropped%29.jpg/330px-A%C3%A9cio_Neves%2C_Michael_Schumacher_e_Didi_%28Cropped%29.jpg' },
            { name: 'Ayrton Senna', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Ayrton_Senna_9_%28cropped%29.jpg/330px-Ayrton_Senna_9_%28cropped%29.jpg' },
            { name: 'Alain Prost', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Festival_automobile_international_2015_-_Photocall_-_065_%28cropped3%29.jpg/330px-Festival_automobile_international_2015_-_Photocall_-_065_%28cropped3%29.jpg' },
            { name: 'Fernando Alonso', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Alonso-68_%2824710447098%29.jpg/330px-Alonso-68_%2824710447098%29.jpg' },
            { name: 'Sebastian Vettel', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Sebastian_Vettel_-_2022236172324_2022-08-24_Champions_for_Charity_-_Sven_-_1D_X_MK_II_-_0418_-_B70I2428_%28cropped%29.jpg/330px-Sebastian_Vettel_-_2022236172324_2022-08-24_Champions_for_Charity_-_Sven_-_1D_X_MK_II_-_0418_-_B70I2428_%28cropped%29.jpg' },
            { name: 'Kimi Räikkönen', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/F12019_Schloss_Gabelhofen_%2822%29_%28cropped%29.jpg/330px-F12019_Schloss_Gabelhofen_%2822%29_%28cropped%29.jpg' },
            { name: 'Jenson Button', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Jenson_Button_2024_WEC_Fuji.jpg/330px-Jenson_Button_2024_WEC_Fuji.jpg' },
            { name: 'Nico Rosberg', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Nico_Rosberg_2016.jpg/330px-Nico_Rosberg_2016.jpg' },
            { name: 'Daniel Ricciardo', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Daniel_Ricciardo_January_2024.jpg/330px-Daniel_Ricciardo_January_2024.jpg' },
            { name: 'Lando Norris', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3968_by_Stepro_%28cropped2%29.jpg/330px-2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3968_by_Stepro_%28cropped2%29.jpg' },
            { name: 'Carlos Sainz', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Formula1Gabelhofen2022_%2804%29_%28cropped2%29.jpg/330px-Formula1Gabelhofen2022_%2804%29_%28cropped2%29.jpg' },
            { name: 'George Russell', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/KingsLeonSilverstne040724_%2828_of_112%29_%2853838006028%29_%28cropped%29.jpg/330px-KingsLeonSilverstne040724_%2828_of_112%29_%2853838006028%29_%28cropped%29.jpg' },
            { name: 'Oscar Piastri', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/2026_Chinese_GP_-_Oscar_Piastri_%28cropped%29_%28cropped%29.jpg/330px-2026_Chinese_GP_-_Oscar_Piastri_%28cropped%29_%28cropped%29.jpg' },
            { name: 'Jacques Villeneuve', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Jacques_Villeneuve_Peugeot_208_T16_Lydden_Hill_2014_006_%28cropped2%29.jpg/330px-Jacques_Villeneuve_Peugeot_208_T16_Lydden_Hill_2014_006_%28cropped2%29.jpg' },
        ],
    },
    {
        id: 'nba',
        title: 'Le meilleur joueur NBA',
        emoji: '🏀',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Michael_Jordan_in_2014.jpg/330px-Michael_Jordan_in_2014.jpg',
        items: [
            { name: 'Michael Jordan', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Michael_Jordan_in_2014.jpg/330px-Michael_Jordan_in_2014.jpg' },
            { name: 'LeBron James', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg/330px-LeBron_James_%2851959977144%29_%28cropped2%29.jpg' },
            { name: 'Shaquille O\'Neal', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/TechCrunch_Disrupt_2023_-_Day_1_%28cropped%29.jpg/330px-TechCrunch_Disrupt_2023_-_Day_1_%28cropped%29.jpg' },
            { name: 'Tim Duncan', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Tim_Duncan_Walks_Verizon_Center%27s_Floor_%28cropped%29_%28cropped%29.jpg/330px-Tim_Duncan_Walks_Verizon_Center%27s_Floor_%28cropped%29_%28cropped%29.jpg' },
            { name: 'Nikola Jokić', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Nikola_Jokic_free_throw_%28cropped%29.jpg/330px-Nikola_Jokic_free_throw_%28cropped%29.jpg' },
            { name: 'Russell Westbrook', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Russell_Westbrook_%28March_21%2C_2022%29_%28cropped%29.jpg/330px-Russell_Westbrook_%28March_21%2C_2022%29_%28cropped%29.jpg' },
            { name: 'Allen Iverson', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Allen_Iverson_headshot.jpg/330px-Allen_Iverson_headshot.jpg' },
            { name: 'Kevin Garnett', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Kevin_Garnett_2008-01-13.jpg/330px-Kevin_Garnett_2008-01-13.jpg' },
            { name: 'Jayson Tatum', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Celtics_at_Wizards_2024-12-044_%28cropped_2%29.jpg/330px-Celtics_at_Wizards_2024-12-044_%28cropped_2%29.jpg' },
            { name: 'Kevin Durant', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kevin_Durant%2C_Paris_2024_%28cropped%29.jpg/330px-Kevin_Durant%2C_Paris_2024_%28cropped%29.jpg' },
        ],
    },
    {
        id: 'horreur',
        title: 'Le meilleur film d\'horreur',
        emoji: '👻',
        img: 'https://image.tmdb.org/t/p/w500/cnniZQGtjK8kh2tsjih4GtkX6bl.jpg',
        items: [
            { name: 'The Shining', img: 'https://image.tmdb.org/t/p/w500/cnniZQGtjK8kh2tsjih4GtkX6bl.jpg' },
            { name: 'L\'Exorciste', img: 'https://image.tmdb.org/t/p/w500/rJU6uv4ADDV0aYdiy7wyIf2nCjS.jpg' },
            { name: 'Hereditary', img: 'https://image.tmdb.org/t/p/w500/5Bz0u7xEyOUnGi4ov3rZKqKYCuH.jpg' },
            { name: 'Get Out', img: 'https://image.tmdb.org/t/p/w500/8WzjAhgc4HvpN3Y6LLCc6AbpIhF.jpg' },
            { name: 'Sans un bruit', img: 'https://image.tmdb.org/t/p/w500/xlJCSHnR7sbaibX3OY97vEmsjxt.jpg' },
            { name: 'Ça', img: 'https://image.tmdb.org/t/p/w500/3SUz0F0I2Bodcj9Ev2pYSWnE9zp.jpg' },
            { name: 'Conjuring', img: 'https://image.tmdb.org/t/p/w500/vOnTvcSsxdJWL9xgauljHHmFSN4.jpg' },
            { name: 'Halloween', img: 'https://image.tmdb.org/t/p/w500/r1ME6ZFxmZ6vFYqt9PHepiIb1t.jpg' },
            { name: 'Scream', img: 'https://image.tmdb.org/t/p/w500/9LfX3IBeByGdFkmkmNztKBr4nYv.jpg' },
            { name: 'Alien', img: 'https://image.tmdb.org/t/p/w500/l8CES84JndFlNfBNMxdLRYaLvI6.jpg' },
            { name: 'The Thing', img: 'https://image.tmdb.org/t/p/w500/dWFzMYk4fNbCeh1DacUfRftevXy.jpg' },
            { name: 'Midsommar', img: 'https://image.tmdb.org/t/p/w500/17pvY55Zr60niVovNvgt72mwvES.jpg' },
            { name: 'The Witch', img: 'https://image.tmdb.org/t/p/w500/cO6EPLw3YfC700TS4JfUaRTGXaZ.jpg' },
            { name: 'Sinister', img: 'https://image.tmdb.org/t/p/w500/qKXxPnsnVbtxFSwhxvKGZTUd5mm.jpg' },
            { name: 'Insidious', img: 'https://image.tmdb.org/t/p/w500/mmyqYYJTMtCBlUNr0JAp5R59X8H.jpg' },
            { name: 'Saw', img: 'https://image.tmdb.org/t/p/w500/3fhUaMnlY72GGuBlzEeKA4brZAb.jpg' },
            { name: 'Smile', img: 'https://image.tmdb.org/t/p/w500/3kbtoJw6ZN0UUQhSuiRbAatr2kV.jpg' },
            { name: 'Talk to Me', img: 'https://image.tmdb.org/t/p/w500/yoZmZOIk35ZuH0WJoakB81ypHUH.jpg' },
            { name: 'Barbarian', img: 'https://image.tmdb.org/t/p/w500/od22ftNnyag0TTxcnJhlsu3aLoU.jpg' },
            { name: 'Jordan Peele Us', img: 'https://image.tmdb.org/t/p/w500/jkT4ML7hV0ghOumyPmxJ3b3GCuw.jpg' },
        ],
    },
    {
        id: 'acteurs',
        title: 'Le meilleur acteur',
        emoji: '🎭',
        img: 'https://image.tmdb.org/t/p/w500/mkdRcVIQl4WZhDf1vXKWTD7HZrZ.jpg',
        items: [
            { name: 'Leonardo DiCaprio', img: 'https://image.tmdb.org/t/p/w500/mkdRcVIQl4WZhDf1vXKWTD7HZrZ.jpg' },
            { name: 'Brad Pitt', img: 'https://image.tmdb.org/t/p/w500/m09Y1YfPPeNYYUSHnnVqahkrC1o.jpg' },
            { name: 'Tom Hanks', img: 'https://image.tmdb.org/t/p/w500/oFvZoKI6lvU03n4YoNGAll9rkas.jpg' },
            { name: 'Denzel Washington', img: 'https://image.tmdb.org/t/p/w500/psYRFKEmhxXubY9LB0zY68c5bcS.jpg' },
            { name: 'Morgan Freeman', img: 'https://image.tmdb.org/t/p/w500/1ahENoyEgKSbRUd0IsydIff7rt1.jpg' },
            { name: 'Robert De Niro', img: 'https://image.tmdb.org/t/p/w500/cT8htcckIuyI1Lqwt1CvD02ynTh.jpg' },
            { name: 'Al Pacino', img: 'https://image.tmdb.org/t/p/w500/m8HAAjq1T75JypKk0v1FFQn4ysZ.jpg' },
            { name: 'Meryl Streep', img: 'https://image.tmdb.org/t/p/w500/g5cVxQBAQ3AXt3LhdBXtbbN47Uc.jpg' },
            { name: 'Scarlett Johansson', img: 'https://image.tmdb.org/t/p/w500/druW5adKddizHNSoPbI0q7Mvn0K.jpg' },
            { name: 'Tom Cruise', img: 'https://image.tmdb.org/t/p/w500/p17SLq4wabXwIYyjXF1Wf5cNnAm.jpg' },
            { name: 'Keanu Reeves', img: 'https://image.tmdb.org/t/p/w500/kEoUZKEG7dzbCESDjd0CKAN1r0n.jpg' },
            { name: 'Ryan Gosling', img: 'https://image.tmdb.org/t/p/w500/lyUyVARQKhGxaxy0FbPJCQRpiaW.jpg' },
            { name: 'Christian Bale', img: 'https://image.tmdb.org/t/p/w500/7Pxez9J8fuPd2Mn9kex13YALrCQ.jpg' },
            { name: 'Joaquin Phoenix', img: 'https://image.tmdb.org/t/p/w500/u38k3hQBDwNX0VA22aQceDp9Iyv.jpg' },
            { name: 'Anthony Hopkins', img: 'https://image.tmdb.org/t/p/w500/dYVQTK1dPrQl1mugeLEWSSmA6Im.jpg' },
            { name: 'Samuel L. Jackson', img: 'https://image.tmdb.org/t/p/w500/AiAYAqwpM5xmiFrAIeQvUXDCVvo.jpg' },
            { name: 'Natalie Portman', img: 'https://image.tmdb.org/t/p/w500/edPU5HxncLWa1YkgRPNkSd68ONG.jpg' },
            { name: 'Emma Stone', img: 'https://image.tmdb.org/t/p/w500/cZ8a3QvAnj2cgcgVL6g4XaqPzpL.jpg' },
            { name: 'Margot Robbie', img: 'https://image.tmdb.org/t/p/w500/au6Hq8nQXJD67mDtl34ZOm8DXrh.jpg' },
            { name: 'Cillian Murphy', img: 'https://image.tmdb.org/t/p/w500/2lKs67r7FI4bPu0AXxMUJZxmUXn.jpg' },
            { name: 'Timothée Chalamet', img: 'https://image.tmdb.org/t/p/w500/dFxpwRpmzpVfP1zjluH68DeQhyj.jpg' },
            { name: 'Florence Pugh', img: 'https://image.tmdb.org/t/p/w500/1Uvfh7xL4U2evkhs0M3C7BbBYFf.jpg' },
        ],
    },
    {
        id: 'sitcoms',
        title: 'La meilleure sitcom',
        emoji: '😂',
        img: 'https://image.tmdb.org/t/p/w500/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg',
        items: [
            { name: 'Friends', img: 'https://image.tmdb.org/t/p/w500/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg' },
            { name: 'Malcolm', img: 'https://image.tmdb.org/t/p/w500/aRd5NJafhAAPXupmTamJGBXonSq.jpg' },
            { name: 'Ma famille d\'abord', img: 'https://image.tmdb.org/t/p/w500/9xIwhzgBoTejiN1zv9VRHUKkpBt.jpg' },
            { name: 'The Office', img: 'https://image.tmdb.org/t/p/w500/2dApsoX4bd98szjrbj5i3syYOh2.jpg' },
            { name: 'Brooklyn Nine-Nine', img: 'https://image.tmdb.org/t/p/w500/A3SymGlOHefSKbz1bCOz56moupS.jpg' },
            { name: 'How I Met Your Mother', img: 'https://image.tmdb.org/t/p/w500/e6PuvBDHqUrJ3dRI2co1G4WXVWf.jpg' },
            { name: 'The Big Bang Theory', img: 'https://image.tmdb.org/t/p/w500/kMhMKG3IVJV8HhMGK7GEY6X73bP.jpg' },
            { name: 'Parks and Recreation', img: 'https://image.tmdb.org/t/p/w500/5IOj62y2Eb2ngyYmEn1IJ7bFhzH.jpg' },
            { name: 'Seinfeld', img: 'https://image.tmdb.org/t/p/w500/jHd9QpsMGphze97dwK8bRQAAOcs.jpg' },
            { name: 'Modern Family', img: 'https://image.tmdb.org/t/p/w500/k5Qg5rgPoKdh3yTJJrLtyoyYGwC.jpg' },
            { name: 'Community', img: 'https://image.tmdb.org/t/p/w500/3KUjDt8XY7w2Ku70UE0SECmv1zP.jpg' },
            { name: 'Arrested Development', img: 'https://image.tmdb.org/t/p/w500/wlt2aqPUJlZgAC1Ga05XuhZtHhT.jpg' },
            { name: 'It\'s Always Sunny', img: 'https://image.tmdb.org/t/p/w500/o0tMMK33JqmtpcWw0H41cEr9xQB.jpg' },
            { name: 'Scrubs', img: 'https://image.tmdb.org/t/p/w500/w7ri7byEYLdciSZOwWHj6TUAX7j.jpg' },
            { name: 'Frasier', img: 'https://image.tmdb.org/t/p/w500/p03cM3OBj9NE0Cvu7Wbd6gNu1BZ.jpg' },
            { name: 'Fresh Prince', img: 'https://image.tmdb.org/t/p/w500/xN3eCrHdRWY3loR5IxCJ613sGyq.jpg' },
            { name: 'Curb Your Enthusiasm', img: 'https://image.tmdb.org/t/p/w500/7nDKHiAijaP1TU8uUjpMlPKaAnj.jpg' },
            { name: 'Superstore', img: 'https://image.tmdb.org/t/p/w500/2tpY5qIYwH85njvjI5BnH4VNA6p.jpg' },
        ],
    },
];

export async function seedDuelDecks(prisma: PrismaClient, ownerId: string) {
    for (const cat of CATEGORIES) {
        const id = `builtin_${cat.id}`;
        const items = cat.items.map((it, i) => ({
            name: it.name,
            imageUrl: isEmoji(it.img) ? null : (it.img || null),
            position: i,
        }));
        // Cover : champ img explicite, sinon 1re image d'item (comme categoryImage).
        const cover = cat.img ?? cat.items.find(it => !isEmoji(it.img))?.img ?? null;
        const base = {
            title: cat.title,
            emoji: cat.emoji,
            imageUrl: cover,
            isPublic: true,
            isBuiltin: true,
            creatorId: ownerId,
        };
        await prisma.duelDeck.upsert({
            where: { id },
            create: { id, ...base, items: { create: items } },
            update: { ...base, items: { deleteMany: {}, create: items } },
        });
    }
    console.log(`✅ ${CATEGORIES.length} Duels intégrés seedés`);
}
